name: PR - GitHub Teams

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - "deployments/cpsi/global/iam/core_github_team/**"
      - ".github/workflows/gh-team-pr.yml"
      - "modules/terraform-github-team/terraform-github-team"
      - "stacks/iam/github_team/**"
      - "ansible-aad/*.yaml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  script:
    name: Detect change scope
    runs-on: ubuntu-latest
    outputs:
      only_ansible: ${{ steps.scope.outputs.only_ansible }}
      gh_groups_changed: ${{ steps.gh.outputs.gh_groups_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Print
        run: |
          echo "base_ref: ${{ github.base_ref }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"

      - name: Detect changed files
        id: scope
        run: |
          git fetch origin "${{ github.base_ref }}"
          FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)

          echo "Changed files:"
          echo "$FILES"

          if echo "$FILES" | grep -qvE '^ansible-aad/.*\.yaml$'; then
            echo "only_ansible=false"
            echo "only_ansible=false" >> $GITHUB_OUTPUT
          else
            echo "only_ansible=true"
            echo "only_ansible=true" >> $GITHUB_OUTPUT
          fi
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Add permissions
        run : chmod +x .github/scripts/check-script.sh
      - name: Run scipt
        id: gh
        if: steps.scope.outputs.only_ansible == 'true'
        run: ./.github/scripts/check-script.sh

  plan:
    name: Validate Terraform Plan (GitHub Teams)
    needs: script
    if: needs.script.outputs.only_ansible != 'true' || needs.script.outputs.gh_groups_changed == 'true'
    runs-on: ubuntu-latest
    environment: terraform-deployment-1_0-reader
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    env:
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_SKIP_PROVIDER_REGISTRATION: true

      TF_ROOT: deployments/cpsi/global/iam/core_github_team

      GITHUB_OWNER: CPSICorp

    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
       
        run: |
          terraform init
        env:
          GITHUB_APP_ID: ${{ vars.APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ vars.APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: |-
            ${{ secrets.TEAM_MGMT_GITHUB_APP_PEM_FILE }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform fmt -check -recursive
          exitcode=0
          terraform plan \
            -lock=false \
            -detailed-exitcode \
            -out=.planfile || exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        env:
          GITHUB_APP_ID: ${{ vars.APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ vars.APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: |-
            ${{ secrets.TEAM_MGMT_GITHUB_APP_PEM_FILE }}

      - name: Terraform Plan Comment
        uses: borchero/terraform-plan-comment@v2.4.0
        continue-on-error: true
        with:
          token: ${{ github.token }}
          planfile: .planfile
          working-directory: ${{ env.TF_ROOT }}
          header: "Terraform Plan: GitHub Teams"